name: 02 - Workflow Events

on:
  # push:
  # pull_request:
  #schedule:
  #- cron: "0 0 * * *" # Every day at midnight UTC
  #- cron: "*/1 * * * *" # Every 1 minute
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "${{github.event_name}}"
