name: 03 - Workflow Runners

on: workflow_dispatch

jobs:
  ubuntu-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show OS
        run: echo "This job runs on ${{ runner.os }}"
      - name: Show OS architecture
        run: echo "This job runs on ${{ runner.arch}}"
      - name: Show Actions details
        run: echo "This job runs on ${{ runner.name }}"
  windows-echo:
    runs-on: windows-latest
    steps:
      - name: Show OS
        run: echo "This job runs on ${{ runner.os }}"
      - name: Show OS architecture
        run: echo "This job runs on ${{ runner.arch}}"
      - name: Show Actions details
        run: echo "This job runs on ${{ runner.name }}"
  macos-echo:
    runs-on: macos-latest
    steps:
      - name: Show OS
        run: echo "This job runs on ${{ runner.os }}"
      - name: Show OS architecture
        run: echo "This job runs on ${{ runner.arch}}"
      - name: Show Actions details
        run: echo "This job runs on ${{ runner.name }}"
