name: 04-using Actions

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # - name: Printing Folders
      #   run: |
      #     echo "Printing folders"
      #     ls -la
      - name: Setup Node
        uses: actions/setup-node@v3
        working-directory: 04-using-actions/04-using-actions
        with:
          node-version: "20"
