name: 04 - Using Actions

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 04-using-actions/04-using-actions
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # - name: Printing Folders
      #   run: |
      #     echo "Printing folders"
      #     ls -la
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - name: Install dependencies
        run: npm ci
      - name: Build App
        run: npm run build
