name: 04-using Actions

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Printing Folders
        run: |
          echo "Printing folders"
          ls -la
