name: 07 - Using Expressions

on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Debug - Print start-up data
        if: ${{inputs.debug}}
        run: |
          echo "Triggered by: ${{github.event_name}}"
          echo "Branch name by: ${{github.ref}}"
          echo "Commit SHA: ${{github.sha}}"
          echo "Runner OS: ${{runner.OS}}"
      - name: Debug - Print when triggered from main
        if: ${{inputs.debug && github.ref}}
        run: echo "Triggered from main branch"
      - name: Gretting
        run: echo "Hello, world!"
