name: 08 - Using Variables

on:
  push:
  workflow_dispatch:

env:
  WORKFLOW_VAR: "I am a workflow env var"
  OVERWRITTEN: "I will be overwritten"
  UNDEFINED_VAR_WITH_DEFAULT: ${{ vars.UNDEFINED_VAR_WITH_DEFAULT || 'default'}}

jobs:
  echo:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: "I am a job env var"
      OVERWRITTEN: "I will be overwritten at the job level"
    steps:
      - name: Print env variables
        env:
          STEP_VAR: "I am a step env var"
          OVERWRITTEN: "I will be overwritten at the step level"
        run: |
          echo "Step env var: ${{env.STEP_VAR}}"
          echo "Step env overwritten: ${{env.OVERWRITTEN}}"
          echo "Job env var: ${{env.JOB_VAR}}"
          echo "Job env overwritten: ${{env.OVERWRITTEN}}"
          echo "Workflow env var: ${{env.WORKFLOW_VAR}}"
          echo "Workflow env overwritten: ${{env.OVERWRITTEN}}"

      - name: Print env variables - 2
        run: |
          echo "Step env var: ${{env.STEP_VAR}}"
          echo "Step env overwritten: ${{env.OVERWRITTEN}}"
          echo "Job env var: ${{env.JOB_VAR}}"
          echo "Job env overwritten: ${{env.OVERWRITTEN}}"
          echo "Workflow env var: ${{env.WORKFLOW_VAR}}"
          echo "Workflow env overwritten: ${{env.OVERWRITTEN}}"
  echo_2:
    runs-on: ubuntu-latest
    steps:
      - name: Print variables
        run: echo "Repositiry variables - ${{ vars.MY_VAR}}"

  echo__prod:
    runs-on: ubuntu-latest
    steps:
      - name: Print Prod variables
        run: |
          echo "Environment Prod variables: ${{ vars.TARGET_VAR }}"
          echo "Environment Prod overwritten variables: ${{vars.OVERWRITTEN_VAR}}"

  echo_undefined:
    runs-on: ubuntu-latest
    steps:
      - name: Print undefined variables
        run: |
          echo "Undefined variable with default value: ${{ env.UNDEFINED_VAR_WITH_DEFAULT }}"
          echo "Undefined variable without default value: ${{ vars.UNDEFINED_VAR }}"
          echo "Undefined variable without default value: ${{ vars.UNDEFINED_VAR_2 }}"
