name: 08 - Using Variables

on:
  push:
  workflow_dispatch:

env:
  WORKFLOW_VAR: "I am a workflow env var"
  OVERWRITTEN: "I will be overwritten"

jobs:
  echo:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: "I am a job env var"
      OVERWRITTEN: "I will be overwritten at the job level"
    steps:
      - name: Print env variables
        env:
          STEP_VAR: "I am a step env var"
          OVERWRITTEN: "I will be overwritten at the step level"
        run: |
          echo "Step env var: ${{env.STEP_VAR}}"
          echo "Step env overwritten: ${{env.OVERWRITTEN}}"
          echo "Job env var: ${{env.JOB_VAR}}"
          echo "Job env overwritten: ${{env.OVERWRITTEN}}"
          echo "Workflow env var: ${{env.WORKFLOW_VAR}}"
          echo "Workflow env overwritten: ${{env.OVERWRITTEN}}"

      - name: Print env variables - 2
        run: |
          echo "Step env var: ${{env.STEP_VAR}}"
          echo "Step env overwritten: ${{env.OVERWRITTEN}}"
          echo "Job env var: ${{env.JOB_VAR}}"
          echo "Job env overwritten: ${{env.OVERWRITTEN}}"
          echo "Workflow env var: ${{env.WORKFLOW_VAR}}"
          echo "Workflow env overwritten: ${{env.OVERWRITTEN}}"
