name: 09 - Using Functions

on:
  pull_request:
  workflow_dispatch:

jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
      - name: "Print PR title"
        run: echo "The PR title is - ${{ github.event.pull_request.title }}"
      - name: "Print PR labels"
        run: |
          cat << EOF
          ${{ toJSON(github.event.pull_request.labels) }}
          EOF
      - name: "Bug step when not cancelled"
        if: ${{!cancelled() && contains(github.event.pull_request.title, 'fix')}}
        run: echo "I am a bug fix"
      - name: "Failing step"
        run: |
          echo "Failing step"
          exit 1
      - name: "I will skipped"
        if: ${{ success() }}
        run: echo "I will be skipped"
      - name: "I will execute"
        if: ${{ failure() }}
        run: echo "I will print if any previous step fails"
      - name: "I will execute"
        if: ${{ !cancelled() }}
        run: echo "I will always print, except when the workflow is cancelled."
      - name: "Bug step post failure and not cancelled"
        if: ${{failure() && !cancelled() && contains(github.event.pull_request.title, 'fix')}}
        run: echo "I am a new bug fix"
      - name: "Bug step when no failure and not cancelled"
        if: ${{!failure() && !cancelled() && contains(github.event.pull_request.title, 'fix')}}
        run: echo "I am a new bug fix"
      - name: "I will execute when cancelled"
        if: ${{ cancelled() }}
        run: echo "I will print when the workflow is cancelled."
      - name: "Sleep for 20 seconds"
        run: sleep 20
